### ISSUE TITLE
[Bug] Allocation can exceed limit

### ISSUE THREAD

**Issue by danielzaiser91** [jshepler/jshepler.ngu.mods#33]
![Image](https://github.com/user-attachments/assets/60cce3e6-c11b-4bb9-b4eb-3aaccefa25f7)

using shift + click on plus sign of r3 on 2 non-active wishes, when i was at 2/3 WIshes, and then removing some assigned r3, it caused what you see in the screenshot 4/3 Wishes.

It's a minor bug i think, and probably not a big issue 🤔

**Comment by danielzaiser91** [comment]
![Image](https://github.com/user-attachments/assets/171eddfe-d25e-4167-b47d-d5fa41ae6281)

ok maybe its a bigger issue than i thought 🤣

**Comment by jshepler** [comment]
Are you a version behind? That bug was fixed in 1.21.

Or at least it was supposed to have been.

**Comment by danielzaiser91** [comment]
In the bottom left it says 1.21

**Comment by jshepler** [comment]
Hmm... Ok, can you give me the steps to reproduce it? I tried what you said above and it didn't work.

**Comment by jshepler** [comment]
Nevermind, got it.. Have to have 0 idle when doing the additional ones.

**Comment by danielzaiser91** [comment]
i noticed it would un-allocate r3 from all wishes, except the limit (for me max 3), after any of the wishes that are researched, reaches the next level.
example: I use this method to allocate ressources to 4/3 --- the 4th wish reaches 2/10 --> r3 is removed from the 4th wish -- it still shows 4/3, but wish#4 only has r1 and r2 assigned (10 quad Energy, 10 Quad Magic, 0 R3)

EDIT:
Actually this described behavior, could be related to the "++" (auto-allocation: on), since i noticed the wishes that were not touched had just "+" (auto-allocation: off)

**Comment by jshepler** [comment]
I've been running the fix all day and haven't noticed any issues, but I really haven't been banging around with it more than the specific steps above. If you'd like to help test, here's the current dev build that has the fix (and some other things in for next update).

[jshepler.ngu.mods.dll.zip](https://github.com/user-attachments/files/19727779/jshepler.ngu.mods.dll.zip)

(attached as a zip because github won't let me attach a dll file)

**Comment by danielzaiser91** [comment]
Alright, I'll check it out today after work, it's 1 am for me

**Comment by danielzaiser91** [comment]
fix seems to work fine, sorry, i totally forgot about this, until i received an email today, that you closed this topic 😅 
tested it just now and yggdrasil page 2/3 error is gone

EDIT: Also tested assigning to more than max wishes, and now it does not allow to set "++" to more than max wishes

**Comment by jshepler** [comment]
cool, thanks for testing
